### ISSUE TITLE
Implementing changes and adding new elements to the report.

### ISSUE THREAD

**Issue by wiktorflorian** [cyfronet-fid/eosc-analyses#5]
This issue mainly combines issues ( #2  , #3  and #4  ). The scope of this issue is to implement changes and add new elements to the [EOSC Data Report](https://docs.google.com/document/d/1KqmLsf7yV03RHrHxwazWsDqw2GQqGznW29uTXJ_feE0/edit#heading=h.ffi5ezrrfh4l) resulting from the review of the report.

- [ ] Implement of the scientific domain part of the [EOSC Data Report](https://docs.google.com/document/d/1KqmLsf7yV03RHrHxwazWsDqw2GQqGznW29uTXJ_feE0/edit#heading=h.ffi5ezrrfh4l) scope of Issue #2.
- [ ] Edit parts of the implemented Issue #3 resulting from the review of this part.
- [ ] Add to the [EOSC Data Report](https://docs.google.com/document/d/1KqmLsf7yV03RHrHxwazWsDqw2GQqGznW29uTXJ_feE0/edit#heading=h.ffi5ezrrfh4l) parts about actual data quality like period year greater than current year or check for html parts in title or description, scope of Issue #4.
- [ ] Add to the introduction part why we compare EOSC transformed data with OpenAIRE dump, what is EOSC, what types of metadata, search criteria and from where.
- [ ] What metadata sources -> OpenAIRE -> data imported into EOSC via monthly dumpy generated by OpenAIRE and submitted via Zenodo.
- [ ] Start a comparative analysis of EOSC and OpenAIRE Later discussion on each point (subsections on PID, author, language etc.). Describe what situation and what problems, what solution to improve the situation.
- [ ] Overall conclusion -> corrective actions.
